### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Viko55555** [oliveirabruno01/babyagi-asi#15]
heres an error that comes up (i want to make a trading bot)

codename ExecutionAgent:
Chain of thoughts: - I need to create tasks to keep following my objective;
- I should start by researching the best trading strategies for the chosen assets and create a plan;
- I need to collect historical and real-time data for the chosen assets;
- I need to preprocess the data and train myself using this data;
- I need to optimize my model, evaluate its performance, and make necessary improvements;
- I need to integrate risk management features and deploy the trading bot on a suitable platform using provided APIs;
- I must keep my progress and any decisions I make along the way informed to the user.

Answer:
def action(self):
    self.task_list.append('Research and define winning trading strategy')
    self.task_list.append('Collect historical and real-time data for the chosen assets')
    self.task_list.append('Preprocess the data and train the model')
    self.task_list.append('Optimize the model and evaluate its performance')
    self.task_list.append('Integrate risk management features and deploy the trading bot')
    self.task_list.append('Keep the user informed of progress and decisions')
    return 'Tasks created successfully.'
Traceback (most recent call last):
  File "C:\ai\babyagi-asi-main\main.py", line 43, in <module>
    + "\n".join([f"{t['task_id']}: {t['task_name']}" for t in AI.task_list])
  File "C:\ai\babyagi-asi-main\main.py", line 43, in <listcomp>
    + "\n".join([f"{t['task_id']}: {t['task_name']}" for t in AI.task_list])
TypeError: string indices must be integers

**Comment by hunterperatt** [comment]
Ive got the same error
